version: "2"
services:
    web: 
        build: .
        ports: 
        - 3000:3000
        command: npm start
        depends_on:
        - db
        environment:
        - DATABASE_URL=postgres://maya:guest@db:5432/names
        - PORT=3000   
    db:
        image: postgres
        ports:
        - 5432:5432
        environment:
        - POSTGRES_USER=maya
        - POSTGRES_PASSWORD=guest
        - POSTGRES_DB=names
